### ISSUE TITLE
Release time

### ISSUE THREAD

**Issue by Xuhao084** [VisualAIKHU/MonoWAD#1]
Dear Authors

What is the approximate time of release?

**Comment by Youngmin-Oh** [comment]
Dear Xuhao084,

Thank you for your interest in our work.

We will release the code as soon as possible.

**Comment by Xuhao084** [comment]
> Dear Xuhao084,
> 
> Thank you for your interest in our work.
> 
> We will release the code as soon as possible.

Dear Authors,

Thanks for the reply. I look forward to your job.

**Comment by Youngmin-Oh** [comment]
We released the code today.
