### ISSUE TITLE
dl.yf.io is down and cannot load models 

### ISSUE THREAD

**Issue by zengxi111** [VisualAIKHU/MonoWAD#5]
It seems that the server for http://dl.yf.io/dla/models is down.I hope you can provide the  models,Thanks!

**Comment by Youngmin-Oh** [comment]
It seems like the server is currently operating normally. However, I've provided an alternative link to download the backbone weights for your convenience. Let me know if you need further assistance.
https://drive.google.com/file/d/1yT6h0J98XLK1mz3nXp5x6K38XIfdkyKS/view?usp=sharing

**Comment by zengxi111** [comment]
I really appreciate your quick and effective response.
